version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: my-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=springboot-transaction
      # - MYSQL_USER=my_user
      # - MYSQL_PASSWORD=my_user_password
    volumes:
      - ./mysql-data:/var/lib/mysql
